codecov:
  notify:
    after_n_builds: 5
  require_ci_to_pass: false

comment:
  behavior: once
  # Don't display the large graph
  layout: "diff, files"

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        informational: true
        target: 100%
