name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: iiasa/actions/.github/workflows/lint.yaml@main
    with:
      type-hint-packages: >-
        numpy
        pandas-stubs
        sdmx1
        types-requests
